/*
 * Hiarc API
 *
 * Welcome to the Hiarc API documentation.
 *
 * API version: 0.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package gohiarc
import (
	"time"
)
// RetentionPolicyApplication struct for RetentionPolicyApplication
type RetentionPolicyApplication struct {
	RetentionPolicy RetentionPolicy `json:"retentionPolicy,omitempty"`
	AppliedAt time.Time `json:"appliedAt,omitempty"`
	ExpiresAt time.Time `json:"expiresAt,omitempty"`
}
