/*
 * Hiarc API
 *
 * Welcome to the Hiarc API documentation.
 *
 * API version: 0.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package gohiarc
// CreateFileRequestAllOf struct for CreateFileRequestAllOf
type CreateFileRequestAllOf struct {
	StorageService string `json:"storageService,omitempty"`
}
