/*
 * Hiarc API
 *
 * Welcome to the Hiarc API documentation.
 *
 * API version: 0.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package gohiarc
// AddFileToCollectionRequest struct for AddFileToCollectionRequest
type AddFileToCollectionRequest struct {
	FileKey string `json:"fileKey,omitempty"`
}
