/*
 * Hiarc API
 *
 * Welcome to the Hiarc API documentation.
 *
 * API version: 0.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package gohiarc
// FileAllOf struct for FileAllOf
type FileAllOf struct {
	VersionCount float32 `json:"versionCount,omitempty"`
}
