/*
 * Hiarc API
 *
 * Welcome to the Hiarc API documentation.
 *
 * API version: 0.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package gohiarc
// CreateRetentionPolicyRequestAllOf struct for CreateRetentionPolicyRequestAllOf
type CreateRetentionPolicyRequestAllOf struct {
	Seconds int32 `json:"seconds,omitempty"`
}
