/*
 * Hiarc API
 *
 * Welcome to the Hiarc API documentation.
 *
 * API version: 0.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package gohiarc
import (
	"time"
)
// UserCredentials struct for UserCredentials
type UserCredentials struct {
	UserKey string `json:"userKey,omitempty"`
	BearerToken string `json:"bearerToken,omitempty"`
	CreatedAt time.Time `json:"createdAt,omitempty"`
	ExpiresAt time.Time `json:"expiresAt,omitempty"`
}
