/*
 * Hiarc API
 *
 * Welcome to the Hiarc API documentation.
 *
 * API version: 0.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package gohiarc
// AddRetentionPolicyToFileRequest struct for AddRetentionPolicyToFileRequest
type AddRetentionPolicyToFileRequest struct {
	RetentionPolicyKey string `json:"retentionPolicyKey,omitempty"`
}
