/*
 * Hiarc API
 *
 * Welcome to the Hiarc API documentation.
 *
 * API version: 0.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package gohiarc
import (
	"time"
)
// FileDirectDownload struct for FileDirectDownload
type FileDirectDownload struct {
	Key string `json:"key,omitempty"`
	DirectDownloadUrl string `json:"directDownloadUrl,omitempty"`
	ExpiresAt time.Time `json:"expiresAt,omitempty"`
}
