/*
 * Hiarc API
 *
 * Welcome to the Hiarc API documentation.
 *
 * API version: 0.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package gohiarc
// AddVersionToFileRequest struct for AddVersionToFileRequest
type AddVersionToFileRequest struct {
	Key string `json:"key,omitempty"`
	StorageService string `json:"storageService,omitempty"`
}
