/*
 * Hiarc API
 *
 * Welcome to the Hiarc API documentation.
 *
 * API version: 0.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package gohiarc
// AccessLevel the model 'AccessLevel'
type AccessLevel string

// List of AccessLevel
const (
	CO_OWNER AccessLevel = "CO_OWNER"
	READ_WRITE AccessLevel = "READ_WRITE"
	READ_ONLY AccessLevel = "READ_ONLY"
	UPLOAD_ONLY AccessLevel = "UPLOAD_ONLY"
)
