/*
 * Hiarc API
 *
 * Welcome to the Hiarc API documentation.
 *
 * API version: 0.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package gohiarc
// CollectionItems struct for CollectionItems
type CollectionItems struct {
	ChildCollections []Collection `json:"childCollections,omitempty"`
	Files []File `json:"files,omitempty"`
}
