/*
 * Hiarc API
 *
 * Welcome to the Hiarc API documentation.
 *
 * API version: 0.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package gohiarc
import (
	"time"
)
// FileDirectUpload struct for FileDirectUpload
type FileDirectUpload struct {
	DirectUploadUrl string `json:"directUploadUrl,omitempty"`
	StorageId string `json:"storageId,omitempty"`
	StorageService string `json:"storageService,omitempty"`
	ExpiresAt time.Time `json:"expiresAt,omitempty"`
}
