/*
 * Hiarc API
 *
 * Welcome to the Hiarc API documentation.
 *
 * API version: 0.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package gohiarc
// AddGroupToFileRequest struct for AddGroupToFileRequest
type AddGroupToFileRequest struct {
	GroupKey string `json:"groupKey,omitempty"`
	AccessLevel AccessLevel `json:"accessLevel,omitempty"`
}
