/*
 * Hiarc API
 *
 * Welcome to the Hiarc API documentation.
 *
 * API version: 0.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package gohiarc

// FindClassificationsRequest struct for FindClassificationsRequest
type FindClassificationsRequest struct {
	Query []map[string]interface{} `json:"query,omitempty"`
}
