/*
 * Hiarc API
 *
 * Welcome to the Hiarc API documentation.
 *
 * API version: 0.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package gohiarc
// AddClassificationToFileRequest struct for AddClassificationToFileRequest
type AddClassificationToFileRequest struct {
	ClassificationKey string `json:"classificationKey,omitempty"`
}
