/*
 * Hiarc API
 *
 * Welcome to the Hiarc API documentation.
 *
 * API version: 0.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package gohiarc
// AllowedFilesRequest struct for AllowedFilesRequest
type AllowedFilesRequest struct {
	Keys []string `json:"keys,omitempty"`
}
