/*
 * Hiarc API
 *
 * Welcome to the Hiarc API documentation.
 *
 * API version: 0.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package gohiarc

// FindGroupsRequest struct for FindGroupsRequest
type FindGroupsRequest struct {
	Query []map[string]interface{} `json:"query,omitempty"`
}
